// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Uuid uuid.UUID
}

type UsersContact struct {
	PhoneNumber string
	Email       pgtype.Text
	TelegramID  pgtype.Int8
	UserUuid    uuid.UUID
}

type UsersDetail struct {
	Name       string
	Surname    string
	Patronymic pgtype.Text
	GroupCode  string
	UserUuid   uuid.UUID
}
