// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (uuid)
values ($1)
returning uuid
`

func (q *Queries) CreateUser(ctx context.Context, uuid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, uuid)
	err := row.Scan(&uuid)
	return uuid, err
}

const createUserContacts = `-- name: CreateUserContacts :one
insert into users_contacts (phone_number, email, telegram_id, user_uuid)
values ($1, $2, $3, $4)
returning phone_number, email, telegram_id, user_uuid
`

type CreateUserContactsParams struct {
	PhoneNumber string
	Email       pgtype.Text
	TelegramID  pgtype.Int8
	UserUuid    pgtype.UUID
}

func (q *Queries) CreateUserContacts(ctx context.Context, arg CreateUserContactsParams) (UsersContact, error) {
	row := q.db.QueryRow(ctx, createUserContacts,
		arg.PhoneNumber,
		arg.Email,
		arg.TelegramID,
		arg.UserUuid,
	)
	var i UsersContact
	err := row.Scan(
		&i.PhoneNumber,
		&i.Email,
		&i.TelegramID,
		&i.UserUuid,
	)
	return i, err
}

const createUserDetails = `-- name: CreateUserDetails :one
insert into users_details (name, surname, patronymic, group_code, user_uuid)
values ($1, $2, $3, $4, $5)
returning name, surname, patronymic, group_code, user_uuid
`

type CreateUserDetailsParams struct {
	Name       string
	Surname    string
	Patronymic pgtype.Text
	GroupCode  string
	UserUuid   pgtype.UUID
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, createUserDetails,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.GroupCode,
		arg.UserUuid,
	)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete
from users
where uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, uuid)
	return err
}

const getUserContacts = `-- name: GetUserContacts :one
select phone_number, email, telegram_id, user_uuid
from users_contacts
where user_uuid = $1
limit 1
`

func (q *Queries) GetUserContacts(ctx context.Context, userUuid pgtype.UUID) (UsersContact, error) {
	row := q.db.QueryRow(ctx, getUserContacts, userUuid)
	var i UsersContact
	err := row.Scan(
		&i.PhoneNumber,
		&i.Email,
		&i.TelegramID,
		&i.UserUuid,
	)
	return i, err
}

const getUserDetails = `-- name: GetUserDetails :one
select name, surname, patronymic, group_code, user_uuid
from users_details
where user_uuid = $1
limit 1
`

func (q *Queries) GetUserDetails(ctx context.Context, userUuid pgtype.UUID) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, getUserDetails, userUuid)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
update users_contacts
set email = $2
where user_uuid = $1
returning phone_number, email, telegram_id, user_uuid
`

type UpdateUserEmailParams struct {
	UserUuid pgtype.UUID
	Email    pgtype.Text
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UsersContact, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.UserUuid, arg.Email)
	var i UsersContact
	err := row.Scan(
		&i.PhoneNumber,
		&i.Email,
		&i.TelegramID,
		&i.UserUuid,
	)
	return i, err
}

const updateUserGroupCode = `-- name: UpdateUserGroupCode :one
update users_details
set group_code = $2
where user_uuid = $1
returning name, surname, patronymic, group_code, user_uuid
`

type UpdateUserGroupCodeParams struct {
	UserUuid  pgtype.UUID
	GroupCode string
}

func (q *Queries) UpdateUserGroupCode(ctx context.Context, arg UpdateUserGroupCodeParams) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, updateUserGroupCode, arg.UserUuid, arg.GroupCode)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
update users_details
set name = $2
where user_uuid = $1
returning name, surname, patronymic, group_code, user_uuid
`

type UpdateUserNameParams struct {
	UserUuid pgtype.UUID
	Name     string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.UserUuid, arg.Name)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const updateUserPatronymic = `-- name: UpdateUserPatronymic :one
update users_details
set patronymic = $2
where user_uuid = $1
returning name, surname, patronymic, group_code, user_uuid
`

type UpdateUserPatronymicParams struct {
	UserUuid   pgtype.UUID
	Patronymic pgtype.Text
}

func (q *Queries) UpdateUserPatronymic(ctx context.Context, arg UpdateUserPatronymicParams) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, updateUserPatronymic, arg.UserUuid, arg.Patronymic)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :one
update users_contacts
set phone_number = $2
where user_uuid = $1
returning phone_number, email, telegram_id, user_uuid
`

type UpdateUserPhoneNumberParams struct {
	UserUuid    pgtype.UUID
	PhoneNumber string
}

func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (UsersContact, error) {
	row := q.db.QueryRow(ctx, updateUserPhoneNumber, arg.UserUuid, arg.PhoneNumber)
	var i UsersContact
	err := row.Scan(
		&i.PhoneNumber,
		&i.Email,
		&i.TelegramID,
		&i.UserUuid,
	)
	return i, err
}

const updateUserSurname = `-- name: UpdateUserSurname :one
update users_details
set surname = $2
where user_uuid = $1
returning name, surname, patronymic, group_code, user_uuid
`

type UpdateUserSurnameParams struct {
	UserUuid pgtype.UUID
	Surname  string
}

func (q *Queries) UpdateUserSurname(ctx context.Context, arg UpdateUserSurnameParams) (UsersDetail, error) {
	row := q.db.QueryRow(ctx, updateUserSurname, arg.UserUuid, arg.Surname)
	var i UsersDetail
	err := row.Scan(
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.GroupCode,
		&i.UserUuid,
	)
	return i, err
}

const updateUserTelegramID = `-- name: UpdateUserTelegramID :one
update users_contacts
set telegram_id = $2
where user_uuid = $1
returning phone_number, email, telegram_id, user_uuid
`

type UpdateUserTelegramIDParams struct {
	UserUuid   pgtype.UUID
	TelegramID pgtype.Int8
}

func (q *Queries) UpdateUserTelegramID(ctx context.Context, arg UpdateUserTelegramIDParams) (UsersContact, error) {
	row := q.db.QueryRow(ctx, updateUserTelegramID, arg.UserUuid, arg.TelegramID)
	var i UsersContact
	err := row.Scan(
		&i.PhoneNumber,
		&i.Email,
		&i.TelegramID,
		&i.UserUuid,
	)
	return i, err
}
