// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Patronymic    *string                `protobuf:"bytes,3,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	GroupCode     string                 `protobuf:"bytes,4,opt,name=group_code,json=groupCode,proto3" json:"group_code,omitempty"`
	UserUuid      string                 `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetails) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserDetails) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *UserDetails) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *UserDetails) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type UserContacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	TelegramId    *int64                 `protobuf:"varint,3,opt,name=telegram_id,json=telegramId,proto3,oneof" json:"telegram_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContacts) Reset() {
	*x = UserContacts{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContacts) ProtoMessage() {}

func (x *UserContacts) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContacts.ProtoReflect.Descriptor instead.
func (*UserContacts) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserContacts) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserContacts) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserContacts) GetTelegramId() int64 {
	if x != nil && x.TelegramId != nil {
		return *x.TelegramId
	}
	return 0
}

func (x *UserContacts) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// CreateUser
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetUserDetails
type GetUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsRequest) Reset() {
	*x = GetUserDetailsRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRequest) ProtoMessage() {}

func (x *GetUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserDetailsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetUserDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsResponse) Reset() {
	*x = GetUserDetailsResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsResponse) ProtoMessage() {}

func (x *GetUserDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDetailsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDetailsResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// GetUserContacts
type GetUserContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContactsRequest) Reset() {
	*x = GetUserContactsRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContactsRequest) ProtoMessage() {}

func (x *GetUserContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContactsRequest.ProtoReflect.Descriptor instead.
func (*GetUserContactsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserContactsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetUserContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      *UserContacts          `protobuf:"bytes,1,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContactsResponse) Reset() {
	*x = GetUserContactsResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContactsResponse) ProtoMessage() {}

func (x *GetUserContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContactsResponse.ProtoReflect.Descriptor instead.
func (*GetUserContactsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserContactsResponse) GetContacts() *UserContacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// DeleteUser
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

// CreateUserDetails
type CreateUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Patronymic    *string                `protobuf:"bytes,3,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	GroupCode     string                 `protobuf:"bytes,4,opt,name=group_code,json=groupCode,proto3" json:"group_code,omitempty"`
	UserUuid      string                 `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDetailsRequest) Reset() {
	*x = CreateUserDetailsRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDetailsRequest) ProtoMessage() {}

func (x *CreateUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*CreateUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserDetailsRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *CreateUserDetailsRequest) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *CreateUserDetailsRequest) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *CreateUserDetailsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type CreateUserDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDetailsResponse) Reset() {
	*x = CreateUserDetailsResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDetailsResponse) ProtoMessage() {}

func (x *CreateUserDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDetailsResponse.ProtoReflect.Descriptor instead.
func (*CreateUserDetailsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserDetailsResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// UpdateUserName
type UpdateUserNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameRequest) Reset() {
	*x = UpdateUserNameRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameRequest) ProtoMessage() {}

func (x *UpdateUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserNameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserNameRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateUserNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameResponse) Reset() {
	*x = UpdateUserNameResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameResponse) ProtoMessage() {}

func (x *UpdateUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserNameResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserNameResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// UpdateUserSurname
type UpdateUserSurnameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSurnameRequest) Reset() {
	*x = UpdateUserSurnameRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSurnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSurnameRequest) ProtoMessage() {}

func (x *UpdateUserSurnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSurnameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSurnameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserSurnameRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserSurnameRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type UpdateUserSurnameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSurnameResponse) Reset() {
	*x = UpdateUserSurnameResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSurnameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSurnameResponse) ProtoMessage() {}

func (x *UpdateUserSurnameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSurnameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSurnameResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserSurnameResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// UpdateUserPatronymic
type UpdateUserPatronymicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Patronymic    *string                `protobuf:"bytes,2,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPatronymicRequest) Reset() {
	*x = UpdateUserPatronymicRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPatronymicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPatronymicRequest) ProtoMessage() {}

func (x *UpdateUserPatronymicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPatronymicRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPatronymicRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserPatronymicRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserPatronymicRequest) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

type UpdateUserPatronymicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPatronymicResponse) Reset() {
	*x = UpdateUserPatronymicResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPatronymicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPatronymicResponse) ProtoMessage() {}

func (x *UpdateUserPatronymicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPatronymicResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPatronymicResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateUserPatronymicResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// UpdateUserGroupCode
type UpdateUserGroupCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	GroupCode     string                 `protobuf:"bytes,2,opt,name=group_code,json=groupCode,proto3" json:"group_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserGroupCodeRequest) Reset() {
	*x = UpdateUserGroupCodeRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserGroupCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupCodeRequest) ProtoMessage() {}

func (x *UpdateUserGroupCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateUserGroupCodeRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserGroupCodeRequest) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

type UpdateUserGroupCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserGroupCodeResponse) Reset() {
	*x = UpdateUserGroupCodeResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserGroupCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupCodeResponse) ProtoMessage() {}

func (x *UpdateUserGroupCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupCodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserGroupCodeResponse) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// CreateUserContacts
type CreateUserContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	TelegramId    *int64                 `protobuf:"varint,3,opt,name=telegram_id,json=telegramId,proto3,oneof" json:"telegram_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserContactsRequest) Reset() {
	*x = CreateUserContactsRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserContactsRequest) ProtoMessage() {}

func (x *CreateUserContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserContactsRequest.ProtoReflect.Descriptor instead.
func (*CreateUserContactsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *CreateUserContactsRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserContactsRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateUserContactsRequest) GetTelegramId() int64 {
	if x != nil && x.TelegramId != nil {
		return *x.TelegramId
	}
	return 0
}

func (x *CreateUserContactsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type CreateUserContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      *UserContacts          `protobuf:"bytes,1,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserContactsResponse) Reset() {
	*x = CreateUserContactsResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserContactsResponse) ProtoMessage() {}

func (x *CreateUserContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserContactsResponse.ProtoReflect.Descriptor instead.
func (*CreateUserContactsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *CreateUserContactsResponse) GetContacts() *UserContacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// UpdateUserPhoneNumber
type UpdateUserPhoneNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPhoneNumberRequest) Reset() {
	*x = UpdateUserPhoneNumberRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPhoneNumberRequest) ProtoMessage() {}

func (x *UpdateUserPhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateUserPhoneNumberRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserPhoneNumberRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type UpdateUserPhoneNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      *UserContacts          `protobuf:"bytes,1,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPhoneNumberResponse) Reset() {
	*x = UpdateUserPhoneNumberResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPhoneNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPhoneNumberResponse) ProtoMessage() {}

func (x *UpdateUserPhoneNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPhoneNumberResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserPhoneNumberResponse) GetContacts() *UserContacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// UpdateUserEmail
type UpdateUserEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserEmailRequest) Reset() {
	*x = UpdateUserEmailRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserEmailRequest) ProtoMessage() {}

func (x *UpdateUserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateUserEmailRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserEmailRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type UpdateUserEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      *UserContacts          `protobuf:"bytes,1,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserEmailResponse) Reset() {
	*x = UpdateUserEmailResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserEmailResponse) ProtoMessage() {}

func (x *UpdateUserEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateUserEmailResponse) GetContacts() *UserContacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// UpdateUserTelegramID
type UpdateUserTelegramIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	TelegramId    *int64                 `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3,oneof" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserTelegramIDRequest) Reset() {
	*x = UpdateUserTelegramIDRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserTelegramIDRequest) ProtoMessage() {}

func (x *UpdateUserTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserTelegramIDRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserTelegramIDRequest) GetTelegramId() int64 {
	if x != nil && x.TelegramId != nil {
		return *x.TelegramId
	}
	return 0
}

type UpdateUserTelegramIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      *UserContacts          `protobuf:"bytes,1,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserTelegramIDResponse) Reset() {
	*x = UpdateUserTelegramIDResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserTelegramIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserTelegramIDResponse) ProtoMessage() {}

func (x *UpdateUserTelegramIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserTelegramIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserTelegramIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateUserTelegramIDResponse) GetContacts() *UserContacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"\x1a\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xab\x01\n" +
	"\vUserDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12#\n" +
	"\n" +
	"patronymic\x18\x03 \x01(\tH\x00R\n" +
	"patronymic\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"group_code\x18\x04 \x01(\tR\tgroupCode\x12\x1b\n" +
	"\tuser_uuid\x18\x05 \x01(\tR\buserUuidB\r\n" +
	"\v_patronymic\"\xa9\x01\n" +
	"\fUserContacts\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12$\n" +
	"\vtelegram_id\x18\x03 \x01(\x03H\x01R\n" +
	"telegramId\x88\x01\x01\x12\x1b\n" +
	"\tuser_uuid\x18\x04 \x01(\tR\buserUuidB\b\n" +
	"\x06_emailB\x0e\n" +
	"\f_telegram_id\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"5\n" +
	"\x12CreateUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.proto.UserR\x04user\"4\n" +
	"\x15GetUserDetailsRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"F\n" +
	"\x16GetUserDetailsResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"5\n" +
	"\x16GetUserContactsRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"J\n" +
	"\x17GetUserContactsResponse\x12/\n" +
	"\bcontacts\x18\x01 \x01(\v2\x13.proto.UserContactsR\bcontacts\"'\n" +
	"\x11DeleteUserRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x14\n" +
	"\x12DeleteUserResponse\"\xb8\x01\n" +
	"\x18CreateUserDetailsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12#\n" +
	"\n" +
	"patronymic\x18\x03 \x01(\tH\x00R\n" +
	"patronymic\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"group_code\x18\x04 \x01(\tR\tgroupCode\x12\x1b\n" +
	"\tuser_uuid\x18\x05 \x01(\tR\buserUuidB\r\n" +
	"\v_patronymic\"I\n" +
	"\x19CreateUserDetailsResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"H\n" +
	"\x15UpdateUserNameRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\x16UpdateUserNameResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"Q\n" +
	"\x18UpdateUserSurnameRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\"I\n" +
	"\x19UpdateUserSurnameResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"n\n" +
	"\x1bUpdateUserPatronymicRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12#\n" +
	"\n" +
	"patronymic\x18\x02 \x01(\tH\x00R\n" +
	"patronymic\x88\x01\x01B\r\n" +
	"\v_patronymic\"L\n" +
	"\x1cUpdateUserPatronymicResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"X\n" +
	"\x1aUpdateUserGroupCodeRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"group_code\x18\x02 \x01(\tR\tgroupCode\"K\n" +
	"\x1bUpdateUserGroupCodeResponse\x12,\n" +
	"\adetails\x18\x01 \x01(\v2\x12.proto.UserDetailsR\adetails\"\xb6\x01\n" +
	"\x19CreateUserContactsRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12$\n" +
	"\vtelegram_id\x18\x03 \x01(\x03H\x01R\n" +
	"telegramId\x88\x01\x01\x12\x1b\n" +
	"\tuser_uuid\x18\x04 \x01(\tR\buserUuidB\b\n" +
	"\x06_emailB\x0e\n" +
	"\f_telegram_id\"M\n" +
	"\x1aCreateUserContactsResponse\x12/\n" +
	"\bcontacts\x18\x01 \x01(\v2\x13.proto.UserContactsR\bcontacts\"^\n" +
	"\x1cUpdateUserPhoneNumberRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\"P\n" +
	"\x1dUpdateUserPhoneNumberResponse\x12/\n" +
	"\bcontacts\x18\x01 \x01(\v2\x13.proto.UserContactsR\bcontacts\"Z\n" +
	"\x16UpdateUserEmailRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"J\n" +
	"\x17UpdateUserEmailResponse\x12/\n" +
	"\bcontacts\x18\x01 \x01(\v2\x13.proto.UserContactsR\bcontacts\"p\n" +
	"\x1bUpdateUserTelegramIDRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12$\n" +
	"\vtelegram_id\x18\x02 \x01(\x03H\x00R\n" +
	"telegramId\x88\x01\x01B\x0e\n" +
	"\f_telegram_id\"O\n" +
	"\x1cUpdateUserTelegramIDResponse\x12/\n" +
	"\bcontacts\x18\x01 \x01(\v2\x13.proto.UserContactsR\bcontacts2\xe4\b\n" +
	"\vUserService\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.proto.CreateUserRequest\x1a\x19.proto.CreateUserResponse\x12M\n" +
	"\x0eGetUserDetails\x12\x1c.proto.GetUserDetailsRequest\x1a\x1d.proto.GetUserDetailsResponse\x12P\n" +
	"\x0fGetUserContacts\x12\x1d.proto.GetUserContactsRequest\x1a\x1e.proto.GetUserContactsResponse\x12A\n" +
	"\n" +
	"DeleteUser\x12\x18.proto.DeleteUserRequest\x1a\x19.proto.DeleteUserResponse\x12V\n" +
	"\x11CreateUserDetails\x12\x1f.proto.CreateUserDetailsRequest\x1a .proto.CreateUserDetailsResponse\x12M\n" +
	"\x0eUpdateUserName\x12\x1c.proto.UpdateUserNameRequest\x1a\x1d.proto.UpdateUserNameResponse\x12V\n" +
	"\x11UpdateUserSurname\x12\x1f.proto.UpdateUserSurnameRequest\x1a .proto.UpdateUserSurnameResponse\x12_\n" +
	"\x14UpdateUserPatronymic\x12\".proto.UpdateUserPatronymicRequest\x1a#.proto.UpdateUserPatronymicResponse\x12\\\n" +
	"\x13UpdateUserGroupCode\x12!.proto.UpdateUserGroupCodeRequest\x1a\".proto.UpdateUserGroupCodeResponse\x12Y\n" +
	"\x12CreateUserContacts\x12 .proto.CreateUserContactsRequest\x1a!.proto.CreateUserContactsResponse\x12b\n" +
	"\x15UpdateUserPhoneNumber\x12#.proto.UpdateUserPhoneNumberRequest\x1a$.proto.UpdateUserPhoneNumberResponse\x12P\n" +
	"\x0fUpdateUserEmail\x12\x1d.proto.UpdateUserEmailRequest\x1a\x1e.proto.UpdateUserEmailResponse\x12_\n" +
	"\x14UpdateUserTelegramID\x12\".proto.UpdateUserTelegramIDRequest\x1a#.proto.UpdateUserTelegramIDResponseB Z\x1elabgrab/user_service/api/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_user_proto_goTypes = []any{
	(*User)(nil),                          // 0: proto.User
	(*UserDetails)(nil),                   // 1: proto.UserDetails
	(*UserContacts)(nil),                  // 2: proto.UserContacts
	(*CreateUserRequest)(nil),             // 3: proto.CreateUserRequest
	(*CreateUserResponse)(nil),            // 4: proto.CreateUserResponse
	(*GetUserDetailsRequest)(nil),         // 5: proto.GetUserDetailsRequest
	(*GetUserDetailsResponse)(nil),        // 6: proto.GetUserDetailsResponse
	(*GetUserContactsRequest)(nil),        // 7: proto.GetUserContactsRequest
	(*GetUserContactsResponse)(nil),       // 8: proto.GetUserContactsResponse
	(*DeleteUserRequest)(nil),             // 9: proto.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 10: proto.DeleteUserResponse
	(*CreateUserDetailsRequest)(nil),      // 11: proto.CreateUserDetailsRequest
	(*CreateUserDetailsResponse)(nil),     // 12: proto.CreateUserDetailsResponse
	(*UpdateUserNameRequest)(nil),         // 13: proto.UpdateUserNameRequest
	(*UpdateUserNameResponse)(nil),        // 14: proto.UpdateUserNameResponse
	(*UpdateUserSurnameRequest)(nil),      // 15: proto.UpdateUserSurnameRequest
	(*UpdateUserSurnameResponse)(nil),     // 16: proto.UpdateUserSurnameResponse
	(*UpdateUserPatronymicRequest)(nil),   // 17: proto.UpdateUserPatronymicRequest
	(*UpdateUserPatronymicResponse)(nil),  // 18: proto.UpdateUserPatronymicResponse
	(*UpdateUserGroupCodeRequest)(nil),    // 19: proto.UpdateUserGroupCodeRequest
	(*UpdateUserGroupCodeResponse)(nil),   // 20: proto.UpdateUserGroupCodeResponse
	(*CreateUserContactsRequest)(nil),     // 21: proto.CreateUserContactsRequest
	(*CreateUserContactsResponse)(nil),    // 22: proto.CreateUserContactsResponse
	(*UpdateUserPhoneNumberRequest)(nil),  // 23: proto.UpdateUserPhoneNumberRequest
	(*UpdateUserPhoneNumberResponse)(nil), // 24: proto.UpdateUserPhoneNumberResponse
	(*UpdateUserEmailRequest)(nil),        // 25: proto.UpdateUserEmailRequest
	(*UpdateUserEmailResponse)(nil),       // 26: proto.UpdateUserEmailResponse
	(*UpdateUserTelegramIDRequest)(nil),   // 27: proto.UpdateUserTelegramIDRequest
	(*UpdateUserTelegramIDResponse)(nil),  // 28: proto.UpdateUserTelegramIDResponse
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: proto.CreateUserResponse.user:type_name -> proto.User
	1,  // 1: proto.GetUserDetailsResponse.details:type_name -> proto.UserDetails
	2,  // 2: proto.GetUserContactsResponse.contacts:type_name -> proto.UserContacts
	1,  // 3: proto.CreateUserDetailsResponse.details:type_name -> proto.UserDetails
	1,  // 4: proto.UpdateUserNameResponse.details:type_name -> proto.UserDetails
	1,  // 5: proto.UpdateUserSurnameResponse.details:type_name -> proto.UserDetails
	1,  // 6: proto.UpdateUserPatronymicResponse.details:type_name -> proto.UserDetails
	1,  // 7: proto.UpdateUserGroupCodeResponse.details:type_name -> proto.UserDetails
	2,  // 8: proto.CreateUserContactsResponse.contacts:type_name -> proto.UserContacts
	2,  // 9: proto.UpdateUserPhoneNumberResponse.contacts:type_name -> proto.UserContacts
	2,  // 10: proto.UpdateUserEmailResponse.contacts:type_name -> proto.UserContacts
	2,  // 11: proto.UpdateUserTelegramIDResponse.contacts:type_name -> proto.UserContacts
	3,  // 12: proto.UserService.CreateUser:input_type -> proto.CreateUserRequest
	5,  // 13: proto.UserService.GetUserDetails:input_type -> proto.GetUserDetailsRequest
	7,  // 14: proto.UserService.GetUserContacts:input_type -> proto.GetUserContactsRequest
	9,  // 15: proto.UserService.DeleteUser:input_type -> proto.DeleteUserRequest
	11, // 16: proto.UserService.CreateUserDetails:input_type -> proto.CreateUserDetailsRequest
	13, // 17: proto.UserService.UpdateUserName:input_type -> proto.UpdateUserNameRequest
	15, // 18: proto.UserService.UpdateUserSurname:input_type -> proto.UpdateUserSurnameRequest
	17, // 19: proto.UserService.UpdateUserPatronymic:input_type -> proto.UpdateUserPatronymicRequest
	19, // 20: proto.UserService.UpdateUserGroupCode:input_type -> proto.UpdateUserGroupCodeRequest
	21, // 21: proto.UserService.CreateUserContacts:input_type -> proto.CreateUserContactsRequest
	23, // 22: proto.UserService.UpdateUserPhoneNumber:input_type -> proto.UpdateUserPhoneNumberRequest
	25, // 23: proto.UserService.UpdateUserEmail:input_type -> proto.UpdateUserEmailRequest
	27, // 24: proto.UserService.UpdateUserTelegramID:input_type -> proto.UpdateUserTelegramIDRequest
	4,  // 25: proto.UserService.CreateUser:output_type -> proto.CreateUserResponse
	6,  // 26: proto.UserService.GetUserDetails:output_type -> proto.GetUserDetailsResponse
	8,  // 27: proto.UserService.GetUserContacts:output_type -> proto.GetUserContactsResponse
	10, // 28: proto.UserService.DeleteUser:output_type -> proto.DeleteUserResponse
	12, // 29: proto.UserService.CreateUserDetails:output_type -> proto.CreateUserDetailsResponse
	14, // 30: proto.UserService.UpdateUserName:output_type -> proto.UpdateUserNameResponse
	16, // 31: proto.UserService.UpdateUserSurname:output_type -> proto.UpdateUserSurnameResponse
	18, // 32: proto.UserService.UpdateUserPatronymic:output_type -> proto.UpdateUserPatronymicResponse
	20, // 33: proto.UserService.UpdateUserGroupCode:output_type -> proto.UpdateUserGroupCodeResponse
	22, // 34: proto.UserService.CreateUserContacts:output_type -> proto.CreateUserContactsResponse
	24, // 35: proto.UserService.UpdateUserPhoneNumber:output_type -> proto.UpdateUserPhoneNumberResponse
	26, // 36: proto.UserService.UpdateUserEmail:output_type -> proto.UpdateUserEmailResponse
	28, // 37: proto.UserService.UpdateUserTelegramID:output_type -> proto.UpdateUserTelegramIDResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_proto_msgTypes[11].OneofWrappers = []any{}
	file_user_proto_msgTypes[17].OneofWrappers = []any{}
	file_user_proto_msgTypes[21].OneofWrappers = []any{}
	file_user_proto_msgTypes[25].OneofWrappers = []any{}
	file_user_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
