// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName            = "/proto.UserService/CreateUser"
	UserService_GetUserDetails_FullMethodName        = "/proto.UserService/GetUserDetails"
	UserService_GetUserContacts_FullMethodName       = "/proto.UserService/GetUserContacts"
	UserService_DeleteUser_FullMethodName            = "/proto.UserService/DeleteUser"
	UserService_CreateUserDetails_FullMethodName     = "/proto.UserService/CreateUserDetails"
	UserService_UpdateUserName_FullMethodName        = "/proto.UserService/UpdateUserName"
	UserService_UpdateUserSurname_FullMethodName     = "/proto.UserService/UpdateUserSurname"
	UserService_UpdateUserPatronymic_FullMethodName  = "/proto.UserService/UpdateUserPatronymic"
	UserService_UpdateUserGroupCode_FullMethodName   = "/proto.UserService/UpdateUserGroupCode"
	UserService_CreateUserContacts_FullMethodName    = "/proto.UserService/CreateUserContacts"
	UserService_UpdateUserPhoneNumber_FullMethodName = "/proto.UserService/UpdateUserPhoneNumber"
	UserService_UpdateUserEmail_FullMethodName       = "/proto.UserService/UpdateUserEmail"
	UserService_UpdateUserTelegramID_FullMethodName  = "/proto.UserService/UpdateUserTelegramID"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// User management
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUserDetails(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error)
	GetUserContacts(ctx context.Context, in *GetUserContactsRequest, opts ...grpc.CallOption) (*GetUserContactsResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// User details management
	CreateUserDetails(ctx context.Context, in *CreateUserDetailsRequest, opts ...grpc.CallOption) (*CreateUserDetailsResponse, error)
	UpdateUserName(ctx context.Context, in *UpdateUserNameRequest, opts ...grpc.CallOption) (*UpdateUserNameResponse, error)
	UpdateUserSurname(ctx context.Context, in *UpdateUserSurnameRequest, opts ...grpc.CallOption) (*UpdateUserSurnameResponse, error)
	UpdateUserPatronymic(ctx context.Context, in *UpdateUserPatronymicRequest, opts ...grpc.CallOption) (*UpdateUserPatronymicResponse, error)
	UpdateUserGroupCode(ctx context.Context, in *UpdateUserGroupCodeRequest, opts ...grpc.CallOption) (*UpdateUserGroupCodeResponse, error)
	// User contacts management
	CreateUserContacts(ctx context.Context, in *CreateUserContactsRequest, opts ...grpc.CallOption) (*CreateUserContactsResponse, error)
	UpdateUserPhoneNumber(ctx context.Context, in *UpdateUserPhoneNumberRequest, opts ...grpc.CallOption) (*UpdateUserPhoneNumberResponse, error)
	UpdateUserEmail(ctx context.Context, in *UpdateUserEmailRequest, opts ...grpc.CallOption) (*UpdateUserEmailResponse, error)
	UpdateUserTelegramID(ctx context.Context, in *UpdateUserTelegramIDRequest, opts ...grpc.CallOption) (*UpdateUserTelegramIDResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserDetails(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDetailsResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserContacts(ctx context.Context, in *GetUserContactsRequest, opts ...grpc.CallOption) (*GetUserContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserContactsResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserDetails(ctx context.Context, in *CreateUserDetailsRequest, opts ...grpc.CallOption) (*CreateUserDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserDetailsResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUserDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserName(ctx context.Context, in *UpdateUserNameRequest, opts ...grpc.CallOption) (*UpdateUserNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserNameResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserSurname(ctx context.Context, in *UpdateUserSurnameRequest, opts ...grpc.CallOption) (*UpdateUserSurnameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserSurnameResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserSurname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserPatronymic(ctx context.Context, in *UpdateUserPatronymicRequest, opts ...grpc.CallOption) (*UpdateUserPatronymicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserPatronymicResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserPatronymic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserGroupCode(ctx context.Context, in *UpdateUserGroupCodeRequest, opts ...grpc.CallOption) (*UpdateUserGroupCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserGroupCodeResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserGroupCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserContacts(ctx context.Context, in *CreateUserContactsRequest, opts ...grpc.CallOption) (*CreateUserContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserContactsResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUserContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserPhoneNumber(ctx context.Context, in *UpdateUserPhoneNumberRequest, opts ...grpc.CallOption) (*UpdateUserPhoneNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserPhoneNumberResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserEmail(ctx context.Context, in *UpdateUserEmailRequest, opts ...grpc.CallOption) (*UpdateUserEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserEmailResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserTelegramID(ctx context.Context, in *UpdateUserTelegramIDRequest, opts ...grpc.CallOption) (*UpdateUserTelegramIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserTelegramIDResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserTelegramID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// User management
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUserDetails(context.Context, *GetUserDetailsRequest) (*GetUserDetailsResponse, error)
	GetUserContacts(context.Context, *GetUserContactsRequest) (*GetUserContactsResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// User details management
	CreateUserDetails(context.Context, *CreateUserDetailsRequest) (*CreateUserDetailsResponse, error)
	UpdateUserName(context.Context, *UpdateUserNameRequest) (*UpdateUserNameResponse, error)
	UpdateUserSurname(context.Context, *UpdateUserSurnameRequest) (*UpdateUserSurnameResponse, error)
	UpdateUserPatronymic(context.Context, *UpdateUserPatronymicRequest) (*UpdateUserPatronymicResponse, error)
	UpdateUserGroupCode(context.Context, *UpdateUserGroupCodeRequest) (*UpdateUserGroupCodeResponse, error)
	// User contacts management
	CreateUserContacts(context.Context, *CreateUserContactsRequest) (*CreateUserContactsResponse, error)
	UpdateUserPhoneNumber(context.Context, *UpdateUserPhoneNumberRequest) (*UpdateUserPhoneNumberResponse, error)
	UpdateUserEmail(context.Context, *UpdateUserEmailRequest) (*UpdateUserEmailResponse, error)
	UpdateUserTelegramID(context.Context, *UpdateUserTelegramIDRequest) (*UpdateUserTelegramIDResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUserDetails(context.Context, *GetUserDetailsRequest) (*GetUserDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDetails not implemented")
}
func (UnimplementedUserServiceServer) GetUserContacts(context.Context, *GetUserContactsRequest) (*GetUserContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserContacts not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) CreateUserDetails(context.Context, *CreateUserDetailsRequest) (*CreateUserDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserDetails not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserName(context.Context, *UpdateUserNameRequest) (*UpdateUserNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserName not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserSurname(context.Context, *UpdateUserSurnameRequest) (*UpdateUserSurnameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserSurname not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserPatronymic(context.Context, *UpdateUserPatronymicRequest) (*UpdateUserPatronymicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPatronymic not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserGroupCode(context.Context, *UpdateUserGroupCodeRequest) (*UpdateUserGroupCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserGroupCode not implemented")
}
func (UnimplementedUserServiceServer) CreateUserContacts(context.Context, *CreateUserContactsRequest) (*CreateUserContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserContacts not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserPhoneNumber(context.Context, *UpdateUserPhoneNumberRequest) (*UpdateUserPhoneNumberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPhoneNumber not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserEmail(context.Context, *UpdateUserEmailRequest) (*UpdateUserEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserEmail not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserTelegramID(context.Context, *UpdateUserTelegramIDRequest) (*UpdateUserTelegramIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserTelegramID not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserDetails(ctx, req.(*GetUserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserContacts(ctx, req.(*GetUserContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserDetails(ctx, req.(*CreateUserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserName(ctx, req.(*UpdateUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserSurname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserSurnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserSurname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserSurname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserSurname(ctx, req.(*UpdateUserSurnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserPatronymic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPatronymicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserPatronymic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserPatronymic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserPatronymic(ctx, req.(*UpdateUserPatronymicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserGroupCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserGroupCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserGroupCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserGroupCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserGroupCode(ctx, req.(*UpdateUserGroupCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUserContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserContacts(ctx, req.(*CreateUserContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserPhoneNumber(ctx, req.(*UpdateUserPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserEmail(ctx, req.(*UpdateUserEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserTelegramID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserTelegramIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserTelegramID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserTelegramID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserTelegramID(ctx, req.(*UpdateUserTelegramIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _UserService_GetUserDetails_Handler,
		},
		{
			MethodName: "GetUserContacts",
			Handler:    _UserService_GetUserContacts_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "CreateUserDetails",
			Handler:    _UserService_CreateUserDetails_Handler,
		},
		{
			MethodName: "UpdateUserName",
			Handler:    _UserService_UpdateUserName_Handler,
		},
		{
			MethodName: "UpdateUserSurname",
			Handler:    _UserService_UpdateUserSurname_Handler,
		},
		{
			MethodName: "UpdateUserPatronymic",
			Handler:    _UserService_UpdateUserPatronymic_Handler,
		},
		{
			MethodName: "UpdateUserGroupCode",
			Handler:    _UserService_UpdateUserGroupCode_Handler,
		},
		{
			MethodName: "CreateUserContacts",
			Handler:    _UserService_CreateUserContacts_Handler,
		},
		{
			MethodName: "UpdateUserPhoneNumber",
			Handler:    _UserService_UpdateUserPhoneNumber_Handler,
		},
		{
			MethodName: "UpdateUserEmail",
			Handler:    _UserService_UpdateUserEmail_Handler,
		},
		{
			MethodName: "UpdateUserTelegramID",
			Handler:    _UserService_UpdateUserTelegramID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
