// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package api

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Uuid pgtype.UUID
}

type UsersContact struct {
	PhoneNumber string
	Email       pgtype.Text
	TelegramID  pgtype.Int8
	UserUuid    pgtype.UUID
}

type UsersDetail struct {
	Name       string
	Surname    string
	Patronymic pgtype.Text
	GroupCode  string
	UserUuid   pgtype.UUID
}
